# Generated by Django 3.1.7 on 2021-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeToGeneId',
            fields=[
                ('product_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('gene_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code_to_gene_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NcbiGeneInfo',
            fields=[
                ('gene_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(blank=True, max_length=64, null=True)),
                ('gene_synonyms', models.TextField(blank=True, null=True)),
                ('gene_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ncbi_gene_info',
                'managed': False,
            },
        ),
    ]
