# Generated by Django 3.1.7 on 2021-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NwCategoryIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('category_name', models.CharField(blank=True, db_column='Category_Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nw_category_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwCategoryLowestNodes',
            fields=[
                ('lowest_node', models.IntegerField(primary_key=True, serialize=False)),
                ('level1', models.IntegerField(blank=True, null=True)),
                ('level2', models.IntegerField(blank=True, null=True)),
                ('level3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nw_category_lowest_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwResearchAreaIds',
            fields=[
                ('research_id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('research_area', models.CharField(blank=True, db_column='Research_Area', max_length=64, null=True)),
            ],
            options={
                'db_table': 'nw_research_area_ids',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='currencies',
            options={'managed': False, 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='dataowners',
            options={'verbose_name_plural': 'Data Owners'},
        ),
        migrations.AlterModelOptions(
            name='mastercurrencies',
            options={'managed': False, 'verbose_name_plural': 'Master Currencies'},
        ),
    ]
