# Generated by Django 3.1.7 on 2021-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0002_auto_20210331_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataowners',
            name='datasheetsuffix',
            field=models.CharField(blank=True, db_column='DatasheetSuffix', default=1, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='dimmensionsproductgroup',
            field=models.PositiveIntegerField(blank=True, db_column='DimmensionsProductGroup', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='ik_flag_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='logo_url',
            field=models.CharField(blank=True, default=1, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='msaccessdatid',
            field=models.PositiveIntegerField(blank=True, db_column='MsAccessDatId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='precedence_listing',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='productpurchasebrand',
            field=models.PositiveIntegerField(blank=True, db_column='ProductPurchaseBrand', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='productsellingbrand',
            field=models.PositiveIntegerField(blank=True, db_column='ProductSellingBrand', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='usa_market_flag_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='web_site_sql_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataowners',
            name='web_site_url',
            field=models.CharField(blank=True, default=1, max_length=45, null=True),
        ),
    ]
