# Generated by Django 3.1.7 on 2021-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0003_auto_20210423_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecords',
            options={},
        ),
    ]
