# Generated by Django 3.1.7 on 2021-04-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0004_auto_20210426_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecords',
            options={'managed': False},
        ),
    ]
