# Generated by Django 3.1.7 on 2021-04-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0006_auto_20210426_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nwcategoryids',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nwcategorylowestnodes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nwresearchareaids',
            options={'managed': False},
        ),
    ]
