# Generated by Django 3.1.7 on 2021-04-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0007_auto_20210426_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nwcategoryids',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nwcategorylowestnodes',
            options={},
        ),
    ]
