# Generated by Django 3.1.7 on 2021-04-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0008_auto_20210426_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nwcategoryids',
            options={'managed': False},
        ),
    ]
